spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
greeting-service:
  greeting: "ola meu brazuca"
  default-value: " que pasa tonto bobo"